name: digital_waqt_azan
description: A new Flutter project for Azan and Prayer Times

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  android_alarm_manager_plus: ^2.1.3
  workmanager: ^0.4.1
  geolocator: ^9.0.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/images/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
    - family: MeQuran
      fonts:
        - asset: assets/fonts/me_quran_volt_newmet.ttf
